name: Cypress Test - Test Project

on:
  push:
    branches: 
      - main
    paths:
      - 'test-project/**.js'
      - 'test-project/**.json'
      - 'test-project/**.yml'

jobs:
  test-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependecies 
        run: npm install
        working-directory: ./test-project

      - name: Run Cypress tests
        run: npm rum cypress:headless
        working-directory: ./test-project

